steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull europe-west2-docker.pkg.dev/$PROJECT_ID/health-jobs/cycling-coach:latest || true
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - europe-west2-docker.pkg.dev/$PROJECT_ID/health-jobs/cycling-coach:latest
      - -t
      - europe-west2-docker.pkg.dev/$PROJECT_ID/health-jobs/cycling-coach:latest
      - .
images:
  - europe-west2-docker.pkg.dev/$PROJECT_ID/health-jobs/cycling-coach:latest
options:
  logging: GCS_ONLY
